config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'mypage' => 'users#mypage'
  resources :users, only: [:edit, :update, :destroy] do
    member do
      get :following, :follower
    end
    collection do
      get :withdrawal_confirmation
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :photographers do
    member do
      post :public_status_switching
    end
  end
  resources :photos do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :rates,    onry: [:create, :destroy]
    collection do
      get :ranking_index
    end
  end
  resources :chats, only: [:show, :create, :destroy]

  get 'search' => "searches#search"
  get "/genres/:id" => 'genres#index', as: 'genre'

  #===== deviseルーティング設定 ======
  devise_for :users,
             path: '',
             path_names: {
               sign_up:      '',
               sign_in:      'login',
               sign_out:     'logout',
               registration: 'signup',
             },
             controllers: {
               registrations: "users/registrations",
               passwords:     "users/passwords",
               sessions:      "users/sessions",
               confirmations: "users/confirmations",
               unlocks:       "users/unlocks",
             }
  devise_scope :user do
    post 'guest_sign_in' , :to => "users/sessions#guest_sign_in"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :comment, presence: true
  validates :comment, length: { in: 2..140 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @photo = Photo.find(params[:photo_id])
    comment = current_user.comments.new(comment_params)
    comment.photo_id = @photo.id
    if comment.save
      flash.now[:notice] = 'コメントを投稿しました'
    else
      flash.now[:alert] = 'コメントを投稿することができませんした'
    end
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    Comment.find_by(photo_id: params[:photo_id], id: params[:id]).destroy
    flash.now[:notice] = "コメントを削除しました"
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!---------------コメント表示部分------------------>

<%= comments.count %>件のコメント
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
      <div class="comment-wwrapper">
        <div class="comment-avatar">
          <%= image_tag comment.user.profile_image.url %>
        </div>
        <div class="comment-text">
          <p><%= "@#{comment.user.name}" %></p>
          <div class="comment-content">
            <%= comment.comment %>
            <% if comment.user == current_user %>
              <%= link_to photo_comment_path(comment.photo.id, comment.id), method: :DELETE, remote: true do %>
                <p>コメント削除</p>
              <% end %>
            <% end %>
          </div>
          <span class="comment-date pull-right">
            <%= comment.created_at.strftime('%Y/%m/%d %H:%M%S') %>
          </span>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

<!----------- コメント入力フォーム ------------>

<%= form_with(model: [@photo, @comment], url: photo_comments_path(@photo)) do |f| %>
  <%= f.text_field :comment, class: 'form_control' %>
  <%= f.submit '送信', class:'btn btn-outline-dark' %>
<% end %>

app/views/comments/_comment_count.html.erb
<div id="comment_count">
  <p><%= photo.comments.count %>件のコメント</p>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <div class="form-group">
    <%= form_with(model: [photo, comment], url: photo_comments_path(photo), method: :POST, remote: true) do |f| %>
      <%= f.text_area :comment, placeholder: 'コメントを入力 ※250文字以内', class: 'form-control mb-2' %>
      <%= f.submit 'コメントを送信', class:'btn btn-outline-dark form-control comment-btn', data: { disable_with: '投稿中...' } %>
    <% end %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<%= render 'comments/comment_count', photo: @photo %>
<% photo.comments.each do |comment| %>
  <% if comment.user == current_user %>
    <li class="current_user_comment-wrapper">
      <div class="comment-avatar">
        <div class="round-circle">
          <% if comment.user.profile_image.blank? %>
            <%= image_tag('no_profile_image.jpg') %>
          <% else %>
            <%= image_tag(comment.user.profile_image.url) %>
          <% end %>
        </div>
      </div>
      <div class="comment-content">
        <h6><%= "@ #{comment.user.name}" %></h6>
        <p><%= comment.comment %></p>
        <span class="comment-date-time"><%= comment.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %></span>
        <%= link_to photo_comment_path(comment.photo.id, comment.id), method: :DELETE, id: 'delete_comment',  data: {confirm: 'コメントを削除しますか' }, remote: true do %>
          <%= image_tag 'comment_destroy.png', alt: 'deleteComment' %>
        <% end %>
      </div>
    </li>
  <% else %>
    <li class="comment-wrapper">
      <div class="comment-avatar">
        <div class="round-circle">
          <% if comment.user.profile_image.blank? %>
            <%= image_tag('no_profile_image.jpg') %>
          <% else %>
            <%= image_tag(comment.user.profile_image.url) %>
          <% end %>
        </div>
      </div>
      <div class="comment-content">
        <h6><%= "@ #{comment.user.name}" %></h6>
        <p><%= comment.comment %></p>
        <span class="comment-date-time"><%= comment.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %>
      </div>
    </li>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#photo-comments").html("<%= j(render 'comments/index', photo: @photo) %>");
$("textarea").val('');
$("#social-menu").html("<%= j(render 'photos/social_menu', photo: @photo) %>");
$("#flash-message").html("<%= j(render 'layouts/flash_message') %>");

app/views/comments/destroy.js.erb
$("#photo-comments").html("<%= j(render 'comments/index', photo: @photo) %>");
$("textarea").val('');
$("#social-menu").html("<%= j(render 'photos/social_menu', photo: @photo) %>");
$("#flash-message").html("<%= j(render 'layouts/flash_message') %>");