config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'mypage' => 'users#mypage'
  resources :users, only: [:edit, :update, :destroy] do
    member do
      get :following, :follower
    end
    collection do
      get :withdrawal_confirmation
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :photographers do
    member do
      post :public_status_switching
    end
  end
  resources :photos do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :rates,    onry: [:create, :destroy]
    collection do
      get :ranking_index
    end
  end
  resources :chats, only: [:show, :create, :destroy]

  get 'search' => "searches#search"
  get "/genres/:id" => 'genres#index', as: 'genre'

  #===== deviseルーティング設定 ======
  devise_for :users,
             path: '',
             path_names: {
               sign_up:      '',
               sign_in:      'login',
               sign_out:     'logout',
               registration: 'signup',
             },
             controllers: {
               registrations: "users/registrations",
               passwords:     "users/passwords",
               sessions:      "users/sessions",
               confirmations: "users/confirmations",
               unlocks:       "users/unlocks",
             }
  devise_scope :user do
    post 'guest_sign_in' , :to => "users/sessions#guest_sign_in"
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, :followed_id, presence: true
  validates_uniqueness_of :follower_id, scope: :followed_id
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow-contents.html.erb
<div class="follower-wrapper">
  <div id="stats">
    <%= render 'relationships/stats', user: user %>
  </div>
  <div id="follow-btn">
    <%= render 'relationships/follow_form', user: user %>
  </div>
</div>

app/views/relationships/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "フォローする", class: 'btn btn-info form-control btn-sm', data: { disable_with: '問い合わせ中...' } %>
<% end %>

app/views/relationships/_follow_form.html.erb
<div id="follow_form">
  <% if user_signed_in? && user.id != current_user.id %>
    <% if current_user.following?(user) %>
       <%= render 'relationships/unfollow', user: user %>
    <% else %>
      <%= render 'relationships/follow', user: user %>
    <% end %>
  <% end %>
  <% unless user_signed_in? %>
    <%= link_to 'フォローする', relationships_path,method: :POST, class: 'btn btn-info form-control' %>
  <% end %>
</div>

app/views/relationships/_stats.html.erb
<div class="stats">
  <a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    フォロー中
  </a>
  <a href="<%= follower_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.follower.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/relationships/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
      html: {method: :delete}, remote: true) do |f| %>
  <%= f.submit "フォローを外す", class: 'btn btn-outline-info form-control btn-sm', data: { disable_with: '問い合わせ中...' } %>
<% end %>

app/views/relationships/create.js.erb
$("#follow-btn").html("<%= j(render 'relationships/follow_form', user: @user) %>");
$("#followers").html('<%= @user.follower.count %>');
$("#profile-stats").html("<%= j(render 'photographers/profile_stats', user: @user) %>");

app/views/relationships/destroy.js.erb
$("#follow-btn").html("<%= j(render 'relationships/follow_form', user: @user) %>");
$("#followers").html('<%= @user.follower.count %>');
$("#profile-stats").html("<%= j(render 'photographers/profile_stats', user: @user) %>");