config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'mypage' => 'users#mypage'
  resources :users, only: [:edit, :update, :destroy] do
    member do
      get :following, :follower
    end
    collection do
      get :withdrawal_confirmation
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :photographers do
    member do
      post :public_status_switching
    end
  end
  resources :photos do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :rates,    onry: [:create, :destroy]
    collection do
      get :ranking_index
    end
  end
  resources :chats, only: [:show, :create, :destroy]

  get 'search' => "searches#search"
  get "/genres/:id" => 'genres#index', as: 'genre'

  #===== deviseルーティング設定 ======
  devise_for :users,
             path: '',
             path_names: {
               sign_up:      '',
               sign_in:      'login',
               sign_out:     'logout',
               registration: 'signup',
             },
             controllers: {
               registrations: "users/registrations",
               passwords:     "users/passwords",
               sessions:      "users/sessions",
               confirmations: "users/confirmations",
               unlocks:       "users/unlocks",
             }
  devise_scope :user do
    post 'guest_sign_in' , :to => "users/sessions#guest_sign_in"
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum user_status: { '一般ユーザー': 0, 'フォトグラファー': 1, '退会済みユーザー': 2 }

  # =============== devise関連===================
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  #========== carrierwaveとの紐つけ==============
  mount_uploader :profile_image, ProfileUploader

  # =========== 各モデルとの関連付け ============
  has_one :photographer, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :follower, through: :passive_relationships, source: :follower
  has_many :rates, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # ========== フォロワー関連メソッド============
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def not_rated?(photo)
    rates.find_by(photo_id: photo.id).nil?
  end

  # =========== ゲストフォトグラファー生成 ===============
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
      user.name = 'Guest Photographer'
    end
  end

  validates :name, :email, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def facebook
    callback_form :facebook
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  protected

  def callback_form(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['amniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_path
    end
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # before_action :create_genres, only: [:create]

  # def create_genres

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to mypage_path, notice: 'ゲストフォトグラファーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :ensure_nomal_user, only: :destroy

  def mypage
    @user = current_user
    @photos = Photo.where("user_id IN (?) OR user_id = ?", @user.following_ids, @user.id).order(id: "DESC")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to mypage_path
    else
      @user = user
      render :edit
    end
  end

  def withdrawal_confirmation
  end

  def destroy
    user = current_user
    user.destroy
    reset_session
    flash[:notice] = '退会処理が完了しました。'
    redirect_to root_path
  end

  def follower
    @title = "Follower"
    @user = User.find(params[:id])
    @users = @user.follower.page(params[:page]).per(8)
    render 'show_follow'
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(8)
    render 'show_follow'
  end

  def ensure_correct_user
    user = User.find(params[:id])
    if user.id != current_user.id
      flash[:alert] = '権限がありません'
      redirect_to mypage_path
    end
  end

  def ensure_nomal_user
    if current_user.email == 'guest@example.com'
      redirect_to mypage_path, alert: 'このアカウントは削除できません。'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :profile_image,
      :area
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="users-container">
  <div class="users-wrapper">
    <h2 class="menu-title">登録情報編集</h2>

    <%= form_with model:@user, local: true do |f| %>

    <div class="field">
      <%= f.label :name, 'ユーザーネーム' %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class:'form-control' %>
    </div>

    <div class="field">
      <%= f.label :profile_image, 'プロフィール写真' %>
      <%= f.file_field :profile_image, class:'form-control' %>
    </div>

    <div class="field">
      <%= f.label :area, '活動地域｜お住まいの地域' %>
      <%= f.text_field :area, autocomplete: 'area', class:'form-control' %>
    </div>

    <div class="action field">
      <%= f.submit '変更を保存', class:'form-control btn btn-dark' %>
    </div>
    <% end %>

    <div class="form action">
      <%= link_to '退会する', withdrawal_confirmation_users_path, data: { disable_with: '問い合わせ中' } %>
    </div>

  </div>
</div>

app/views/users/mypage.html.erb
<div class="mypage-container">
  <div class="mypage-title-fixed">
    <h2 class="menu-title">マイページ</h2>
  </div>
  <div clsss="mypage-wrapper">
    <div class="mypage-profile-wrapper">
      <h4 class="mypage-user-status"><%= @user.user_status %></h4>
      <div class="mypage-user-top">
        <div class="mypage-user-image">
          <div class="round-circle">
            <% if @user.profile_image.blank? %>
              <%= image_tag asset_path('no_profile_image.jpg') %>
            <% else %>
              <%= image_tag @user.profile_image.url %>
            <% end %>
          </div>
        </div>
        <h2 class="mb-0 mt-2"><%= @user.name %></h2>
      </div>
      <table class="table table-borderless text-center mb-0 mt-2">
        <% if @user.user_status == 'フォトグラファー' %>
          <tr>
            <td class="p-1">フォロワー</td>
            <td class="p-1">フォロー中</td>
            <td class="p-1">　投稿数　</td>
          </tr>
          <tr>
            <th class="p-1"><%= link_to @user.follower.count, follower_user_path(@user) %></th>
            <th class="p-1"><%= link_to @user.following.count, following_user_path(@user) %></th>
            <th class="p-1"><%= link_to @user.photos.count, photographer_path(@user.photographer) %></th>
          </tr>
        <% else %>
          <p class="mt-2">フォロー中：<%= link_to @user.following.count, following_user_path(@user) %></p>
        <% end %>
      </table>
      <div class="mypage-setting-btn">
        <i>
          <%= link_to edit_user_path(@user), class: 'btn btn-outline-dark form-control' do %>
            <span class="fa fa-cog"></span>
          <% end %>
        </i>
        <btn>
          <% if @user.user_status == 'フォトグラファー' %>
            <%= link_to 'プロフィールページを見る', photographer_path(@user.photographer), class: 'btn btn-info form-control' %>
          <% else %>
            <%= link_to 'フォトグラファー登録する', new_photographer_path, class: 'btn btn-info form-control' %>
          <% end %>
        </btn>
      </div>
      <hr class="mb-0">
    </div>

    <!--ここからフィードの記述-->
    <div class="mypage-photos-wrapper">
      <% @photos.each do |photo| %>
        <%= link_to photo_path(photo) do %>
          <div class="photo-flame">
            <div class="square">
              <%= image_tag photo.photo_image.url %>
            </div>
            <%= link_to photographer_path(photo.user.photographer) do %>
            <div class="mypage-feed-user-profile">
              <div class="mypage-fiid-user-profile-image">
                <div class="round-circle">
                  <% if photo.user.photographer.photographer_profile_image.blank? %>
                    <%= image_tag('no_profile_image.jpg') %>
                  <% else %>
                    <%= image_tag(photo.user.photographer.photographer_profile_image.url) %>
                  <% end %>
                </div>
              </div>
              <h3 class="mypage-feed-profile-name">
                <%= photo.user.photographer.name %>
              </h3>
            </div>
            <% end %>
            <div class="photo-edit-menu">
              <%= render 'photos/photo_edit_menu', photo: photo %>
            </div>
            <div class="mypage-favorite-btn" id="favorites_btn_<%= photo.id %>">
              <%= render 'favorites/favorite', photo: photo %>
            </div>
          </div>
          <div class="mypage-feed-datetime">
            <%= photo.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %>
          </div>
        <% end %>
        <hr class="mt-1">
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="show-follow-container">
  <h2 class="menu-title"><%= @title %>(<%= @users.count %>)</h2>
  <h4 class="show-follow-user-name"><%= @user.photographer.name %></h4>
  <div class="follow-wrapper">
    <% @users.each do |user| %>
      <div class="follow-user">
        <% if user.user_status == 'フォトグラファー' %>
          <%= link_to photographer_path(user.photographer) do %>
            <div class="square">
              <% if user.photographer.photographer_profile_image.blank? %>
                <%= image_tag('no_profile_image.jpg') %>
              <% else %>
                <%= image_tag user.photographer.photographer_profile_image.url %>
              <% end %>
            </div>
            <div class="follow-photographer-name">
              <%= user.photographer.name %>
            </div>
          <% end %>
        <% else %>
          <div class="square">
            <% if user.profile_image.blank? %>
              <%= image_tag('no_profile_image.jpeg') %>
            <% else %>
              <%= image_tag user.profile_image.url %>
            <% end %>
          </div>
          <div class="follow-photographer-name">
            <%= user.name %>
          </div>
        <% end %>
        <label class="follow-user-status">
          <p><%= user.user_status %></p>
        </label>
      </div>
    <% end %>
  </div>
</div>

app/views/users/withdrawal_confirmation.html.erb
<div class="users-container">
  <div class="users-wrapper">
    <h2 class="mb-4">本当に退会しますか？</h2>
    <%= link_to '退会しない', mypage_path, class: 'btn btn-primary form-control mb-4' %>
    <%= link_to '退会する', user_path(current_user), method: :DELETE, class: 'btn btn-danger form-control mb-4' %>
  </div>
</div>