config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'mypage' => 'users#mypage'
  resources :users, only: [:edit, :update, :destroy] do
    member do
      get :following, :follower
    end
    collection do
      get :withdrawal_confirmation
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :photographers do
    member do
      post :public_status_switching
    end
  end
  resources :photos do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :rates,    onry: [:create, :destroy]
    collection do
      get :ranking_index
    end
  end
  resources :chats, only: [:show, :create, :destroy]

  get 'search' => "searches#search"
  get "/genres/:id" => 'genres#index', as: 'genre'

  #===== deviseルーティング設定 ======
  devise_for :users,
             path: '',
             path_names: {
               sign_up:      '',
               sign_in:      'login',
               sign_out:     'logout',
               registration: 'signup',
             },
             controllers: {
               registrations: "users/registrations",
               passwords:     "users/passwords",
               sessions:      "users/sessions",
               confirmations: "users/confirmations",
               unlocks:       "users/unlocks",
             }
  devise_scope :user do
    post 'guest_sign_in' , :to => "users/sessions#guest_sign_in"
  end
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  belongs_to :user
  has_many :photographer_genre_maps, foreign_key: 'photographer_id',
                                     dependent: :destroy
  has_many :genres, through: :photographer_genre_maps

  mount_uploader :photographer_profile_image, PhotographerProfileImageUploader
  mount_uploader :cover_image, CoverUploader

  # =============== ジャンル保存用の記述 ==================
  def save_photographer_genres(save_genres)
    current_genres = genres.pluck(:name) unless genres.nil?
    old_genres = current_genres - save_genres
    new_genres = save_genres - current_genres

    old_genres.each do |old_name|
      genres.delete Genre.find_by(name: old_name)
    end

    new_genres.each do |new_name|
      photographer_genre = Genre.find_or_create_by(name: new_name)
      genres << photographer_genre
    end
  end

  # =========== フォトグラファー検索用の記述 ==============
  def self.search(word)
    if word == ""
      Photographer.includes(:user).order(id: "DESC")
    else
      name = Photographer.where('name LIKE?', "%#{word}%")
      genres = Photographer.joins(:genres).where('genres.name LIKE?', "%#{word}%")
      name += genres
      photographers = name.uniq
      photographers
    end
  end

  validates :name, presence: true
  validates :introduction, length: { maximum: 250 }
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :public_status_confirmation, only: [:show]
  before_action :ensure_correct_photographer, only: [:edit, :update, :destroy, :public_status_switching]

  def new
    @photographer = Photographer.new
    @user = current_user
  end

  def create
    photographer = Photographer.new(photographer_params)
    photographer.user_id = current_user.id
    if photographer.save
      if params[:photographer][:genre].present?
        genres = params[:photographer][:genre].split(/[[:blank:]]+/)
        # photographerインスタンスに対してsave_photographerメソッド呼び出し
        photographer.save_photographer_genres(genres)
      end
      user = photographer.user
      user.update(user_status: "フォトグラファー", photographer_id: photographer.id)
      flash[:notice] = "フォトグラファー登録が完了しました"
      redirect_to mypage_path
    else
      @photographer = photographer
      @user = current_user
      render :new
    end
  end

  def show
    @photographer = Photographer.find(params[:id])
    @user = @photographer.user
    @photos = @user.photos.order(id: 'DESC')
  end

  def edit
    @photographer = Photographer.find(params[:id])
    genre_names_array = @photographer.genres.pluck(:name)
    @genre_names = genre_names_array.join(' ')
  end

  def update
    photographer = Photographer.find(params[:id])
    if photographer.update(photographer_params)
      if params[:photographer][:genre].present?
        genres = params[:photographer][:genre].split(/[[:blank:]]+/)
        # photographerインスタンスに対してsave_photographerメソッド呼び出し
        photographer.save_photographer_genres(genres)
      end
      flash[:notice] = "プロフィールを編集しました"
      redirect_to photographer_path(photographer)
    else
      @photographer = photographer
      render :edit
    end
  end

  def index
    @photographers = Photographer.where(public_status: true).page(params[:page]).per(8).order(id: 'DESC')
  end

  # プロフィールの公開設定を切り替える
  def public_status_switching
    photographer = Photographer.find(params[:id])
    photographer.toggle!(:public_status)
    flash[:notice] = "プロフィールの公開設定を更新しました"
    redirect_to photographer_path(photographer)
  end

  # プロフィールの公開設定falseだったらリダイレクト
  # 　でも本人だけはアクセスできる。
  def public_status_confirmation
    @photographer = Photographer.find(params[:id])
    if current_user.present? && current_user.id == @photographer.user.id
      true
    else
      if @photographer.public_status == false
        flash[:notice] = "#{@photographer.name}さんはプロフィールを公開していません"
        redirect_to request.referer
      else
        true
      end
    end
  end

  # 本人のみ編集が可能
  def ensure_correct_photographer
    photographer = Photographer.find(params[:id])
    if photographer.user.id != current_user.id
      flash[:alert] = "権限がありません"
      redirect_to mypage_path
    end
  end

  private

  def photographer_params
    params.require(:photographer).permit(
      :name,
      :area,
      :introduction,
      :photographer_profile_image,
      :cover_image,
      :instagram_url,
      :facebook_url,
      :public_status
    )
  end
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/views/photographers/_list.html.erb
<div class="photos-wrapper">
  <% @photographers.each do |photographer| %>
    <div class="photographer-info">
      <%= link_to photographer_path(photographer), class: "photographer-image" do %>
        <div class="square">
          <% if photographer.photographer_profile_image.blank? %>
            <%= image_tag('no_profile_image.jpg') %>
          <% else %>
            <%= image_tag photographer.photographer_profile_image.url %>
          <% end %>
        </div>
        <h5><%= photographer.name %></h5>
      <% end %>
    </div>
  <% end %>
</div>

app/views/photographers/_profile_stats.html.erb
<div class="profile-stats">
  <p>
    <%= link_to follower_user_path(user) do %>
      Follower: <%= user.follower.count %>
    <% end %>
    <%= link_to following_user_path(user) do %>
      Following: <%= user.following.count %>
    <% end %>
    Photos: <%= user.photos.count %>
  </p>
</div>

app/views/photographers/_top_profile.html.erb
<div class="photographer-wrapper">
  <div class="photographer-icon">
    <%= link_to photographer_path(user.photographer) do %>
      <div class="round-circle">
        <% if user.photographer.photographer_profile_image.blank? %>
          <%= image_tag('no_profile_image.jpg') %>
        <% else %>
          <%= image_tag(user.photographer.photographer_profile_image.url) %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="photographer-information">
    <h4><%= user.photographer.name %></h4>
    <%= render 'relationships/follow-contents', user: user %>
  </div>
</div>

app/views/photographers/edit.html.erb
<div class="users-container">
  <div class="users-wrapper">
    <h2 class="menu-title">プロフィール編集</h2>
    <%= form_with model:@photographer, local: true do |f| %>

      <%= render 'shered/errors', model: f.object %>

      <div class="field">
        <%= f.label :name, 'フォトグラファーネーム' %>
        <%= f.text_field :name, value: @photographer.name, autofocus: true, class:'form-control' %>
      </div>

      <div class="field">
        <%= f.label :photographer_profile_image, 'プロフィール写真' %>
        <%= f.file_field :photographer_profile_image %>
      </div>

      <div class="field">
        <%= f.label :cover_image, 'カバー写真' %>
        <%= f.file_field :cover_image %>
      </div>

      <div class="field">
        <%= f.label :area, '活動地域' %>
        <%= f.text_field :area, value: @photographer.area, class:'form-control' %>
      </div>

      <div class="field">
        <%= f.label :introduction, '紹介文' %>
        <textarea class="form-control" rows="5" name="photographer[introduction]" id="photographer_introduction"><%= @photographer.introduction %></textarea>
      </div>

      <div class="field">
        <%= f.label :genre, '撮影ジャンル' %>
        <%= f.text_field :genre, value: @genre_names, placeholder: '人物 風景 料理', class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :instagram_url, 'インスタグラムURL' %>
        <%= f.text_field :instagram_url, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :facebook_url, 'フェイスブックURL' %>
        <%= f.text_field :facebook_url, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :public_status, 'プロフィール公開設定' %>
        <select class="form-control" id="sel1" aria-label="Default select example" name="photographer[public_status]" id="photographer_public_status">
          <option value="true">公開する</option>
          <option value="false">まだ公開しない</option>
        </select>
      </div>

      <div class="action field">
        <%= f.submit '編集内容を保存する', class:"form-control btn btn-dark", data: { disable_with: '保存中...' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/photographers/index.html.erb
<div class="main-container">
  <h2 class="menu-title mt-5">フォトグラファー一覧</h2>
  <%= render 'photographers/list', photographers: @photographers %>

  <%= paginate @photographers %>
</div>

app/views/photographers/new.html.erb
<div class="users-container">
  <div class="users-wrapper">
    <h2 class="menu-title">フォトグラファー登録</h2>
    <%= form_with model:@photographer, local: true do |f| %>

      <%= render 'shered/errors', model: f.object %>

      <div class="field">
        <%= f.label :name, 'フォトグラファーネーム ※必須' %>
        <%= f.text_field :name, value: @user.name, autofocus: true, class:'form-control' %>
      </div>

      <div class="field">
        <%= f.label :photographer_profile_image, 'プロフィール写真' %>
        <%= f.file_field :photographer_profile_image %>
      </div>

      <div class="field">
        <%= f.label :cover_image, 'カバー写真' %>
        <%= f.file_field :cover_image %>
      </div>

      <div class="field">
        <%= f.label :area, '活動地域' %>
        <%= f.text_field :area, value: @user.area, class:'form-control' %>
      </div>

      <div class="field">
        <%= f.label :genre, '撮影ジャンル（スペースで区切って入力' %>
        <%= f.text_field :genre, placeholder: "人物 料理 風景", class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :introduction, '紹介文 ※250文字以内' %>
        <textarea class="form-control" rows="5" name="photographer[introduction]" id="photographer_introduction"></textarea>
      </div>

      <div class="field">
        <%= f.label :instagram_url, 'インスタグラムURL' %>
        <%= f.text_field :instagram_url, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :facebook_url, 'フェイスブックURL' %>
        <%= f.text_field :facebook_url, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :public_status, 'プロフィール公開設定' %>
        <select class="form-control" id="sel1" aria-label="Default select example" name="photographer[public_status]" id="photographer_public_status">
          <option value="true">公開する</option>
          <option selected="selected" value="false">まだ公開しない</option>
        </select>
      </div>

      <div class="action field">
        <%= f.submit '登録を完了する', class: 'form-control btn btn-info', data: { disable_with: '登録中...' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/photographers/show.html.erb
<div class="profile-container">
  <div class="profile-main-visual">
    <% if @photographer.cover_image.blank? %>
      <%= image_tag('no_cover_image.jpg') %>
    <% else %>
      <%= image_tag @photographer.cover_image.url %>
    <% end %>
  </div>

  <div class="profile-wrapper">
    <div class="profile-photographer-wrapper">
      <div class="profile-photographer-image">
        <div class=image>
        <div class="round-circle">
          <% if @photographer.photographer_profile_image.blank? %>
            <%= image_tag('no_profile_image.jpg') %>
          <% else %>
            <%= image_tag @photographer.photographer_profile_image.url %>
          <% end %>
        </div>
        </div>
      </div>
      <div class="photographer-name">
        <h1><%= @photographer.name %></h1>
      </div>
    </div>
    <div class="profile-detail">
      <div id="profile-stats">
        <%= render 'photographers/profile_stats', user: @user %>
      </div>
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="profile-settings-btn">
          <btn>
            <% if @photographer.public_status == false %>
              <%= link_to '公開停止中', public_status_switching_photographer_path(@photographer), method: :POST, class: 'btn btn-outline-success form-control' %>
            <% else %>
              <%= link_to 'プロフィール公開中', public_status_switching_photographer_path(@photographer), method: :POST, class: 'btn btn-success form-control' %>
            <% end %>
          </btn>
          <i>
            <%= link_to edit_photographer_path(@photographer), class: 'btn btn-outline-dark form-control' do %>
              <span class="fa fa-cog"></span>
            <% end %>
          </i>
        </div>
      <% else %>
        <div class="profile-settings-btn">
          <btn id="follow-btn">
            <%= render 'relationships/follow_form', user: @user %>
          </btn>
          <i>
            <%= link_to chat_path(@user.id), class: 'btn btn-outline-dark form-control' do %>
              <span class="fa fa-envelope fa-lg"></span>
            <% end %>
          </i>
        </div>
      <% end %>
      <hr>
      <div class="profile-introduction">
        <p><%= @photographer.introduction %></p>
      </div>
      <div class="profile-gemre-item">
        <% @photographer.genres.each do |genre| %>
          <%= link_to genre.name, genre_path(genre), class: 'btn btn-sm btn-outline-dark mb-1' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="profile-photo-gallery">
    <h2 class="menu-title">PHOTO GALLERY</h2>
    <%= render 'photos/list', photos: @photos %>
  </div>
</div>